source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ABTSoftware/PodSpecs.git'

platform :ios, '13.0'
use_frameworks!

def share_pods
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'

end

target 'RXTestes' do
	share_pods
end

